export const dummyProject = {
  id: 1,
  team_id: 1,
  customer_id: 1,
  name: "Foo Bar",
  active: true,
  billable: true,
  estimated_hours: 10,
  rate: 60,
  color_hex: "#8E59FF",
  start_date: {
    date: "2020-08-10 10:00:00",
    timezone_type: 3,
    timezone: "UTC",
  },
  end_date: {
    date: "2020-08-10 10:00:00",
    timezone_type: 3,
    timezone: "UTC",
  },
  project_type: "time_and_material",
  budget: 1000,
  created_at: {
    date: "2020-08-10 10:00:00",
    timezone_type: 3,
    timezone: "UTC",
  },
  updated_at: {
    date: "2020-08-10 10:00:00",
    timezone_type: 3,
    timezone: "UTC",
  },
  deleted_at: {
    date: "2020-08-10 10:00:00",
    timezone_type: 3,
    timezone: "UTC",
  },
};

export const dummyTimeEntry = {
  id: 1,
  team_id: 1,
  customer_id: 1,
  user_id: 1,
  project_id: 1,
  invoice_id: null,
  description: "Test",
  billable: true,
  billed: false,
  started_at: {
    date: "2020-08-10 10:00:00",
    timezone_type: 3,
    timezone: "UTC",
  },
  stopped_at: null,
  duration: 3600,
  created_at: {
    date: "2020-01-01",
    timezone_type: 3,
    timezone: "UTC",
  },
  updated_at: {
    date: "2020-01-01",
    timezone_type: 3,
    timezone: "UTC",
  },
  deleted_at: {
    date: "2020-01-01",
    timezone_type: 3,
    timezone: "UTC",
  },
};

export const suggestedTimeEntries = [
  {
    id: 2,
    team_id: 1,
    customer_id: 1,
    user_id: 1,
    project_id: 2,
    invoice_id: null,
    description: "Foo",
    billable: true,
    billed: false,
    started_at: {
      date: "2020-08-15 10:00:00",
      timezone_type: 3,
      timezone: "UTC",
    },
    stopped_at: {
      date: "2020-08-15 11:00:00",
      timezone_type: 3,
      timezone: "UTC",
    },
    duration: 3600,
    created_at: {
      date: "2020-01-01",
      timezone_type: 3,
      timezone: "UTC",
    },
    updated_at: null,
    deleted_at: null,
  },
  {
    id: 3,
    team_id: 1,
    customer_id: 1,
    user_id: 1,
    project_id: 2,
    invoice_id: null,
    description: "Bar",
    billable: true,
    billed: false,
    started_at: {
      date: "2020-08-15 10:00:00",
      timezone_type: 3,
      timezone: "UTC",
    },
    stopped_at: {
      date: "2020-08-15 11:00:00",
      timezone_type: 3,
      timezone: "UTC",
    },
    duration: 3600,
    created_at: {
      date: "2020-01-01",
      timezone_type: 3,
      timezone: "UTC",
    },
    updated_at: null,
    deleted_at: null,
  },
  {
    id: 4,
    team_id: 1,
    customer_id: 1,
    user_id: 1,
    project_id: 2,
    invoice_id: null,
    description: "Baz",
    billable: true,
    billed: false,
    started_at: {
      date: "2020-08-15 10:00:00",
      timezone_type: 3,
      timezone: "UTC",
    },
    stopped_at: {
      date: "2020-08-15 11:00:00",
      timezone_type: 3,
      timezone: "UTC",
    },
    duration: 3600,
    created_at: {
      date: "2020-01-01",
      timezone_type: 3,
      timezone: "UTC",
    },
    updated_at: null,
    deleted_at: null,
  },
];
